apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# it is possible to customize namespace, commented out for the lab
# namespace: cp4ba1

commonLabels:
  stack: dev1

commonAnnotations:
  ibmSupport: 1-800-IBM-SERV

bases:
- ../../base

patches:
- path: lc-ldap-server-patch.yaml
- path: lc-license-type-patch.yaml
