apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# it is possible to customize namespace, commented out for the lab
# namespace: cp4ba1

commonLabels:
  stack: prod1

commonAnnotations:
  ibmSupport: 1-800-IBM-SERV

bases:
- ../../base

patchesJson6902:
- path: multi-json-patch.json
  target:
    group: icp4a.ibm.com
    version: v1
    kind: ICP4ACluster
    name: icp4adeploy
